#!/bin/bash

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run a Django management command.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        cd blog/

        python3 manage.py "$@"

        cd ../
    fi
fi