#!/bin/bash

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run the Django server.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        ./scripts/manage runserver
    fi
fi